### ISSUE TITLE
C# 如何引用插件？

### ISSUE THREAD

**Issue by Fire2Sky** [WallBreaker2/op#10]
1使用win10 X64系统，注册插件。
2使用vs2019创建C#项目，在引用只是发现opLib，没有op。
3使用python x64注册成功，使用demo是可以的。

**Comment by jonathanpeng** [comment]
`[DllImport(@"op_x64.dll", EntryPoint = @"?FindWindowW@libop@@QEAAJPEB_W0PEAJ@Z")]
        public static extern IntPtr FindWindow(string className, string title);`

**Comment by WallBreaker2** [comment]
百度或者进群查看相应教程
