### ISSUE TITLE
是否有可以根据句柄画矩形的功能？

### ISSUE THREAD

**Issue by rwerplus** [WallBreaker2/op#100]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by flaot** [comment]
说的应该是窗口句柄吧
使用接口`GetClientRect`获取窗口在桌面的位置及大小
然后用win32API创建自定义透明窗口，在窗口中用GDI函数画矩形
