### ISSUE TITLE
Tesseract couldn't load any languages!

### ISSUE THREAD

**Issue by rwerplus** [WallBreaker2/op#101]
**Describe the bug**
在electron中免注册调用dll启动后报错Tesseract couldn't load any languages!
**To Reproduce**
我在nodejs中使用获取当前执行目录加\\xx.dll可以调用，但是换了op之后会报错，不知道是不是路径问题
op注册到系统中时nodejs使用winax是可以调用的，但是免注册一直有问题
![image](https://github.com/WallBreaker2/op/assets/48611415/ecf91648-d5dd-4735-bcbf-7bfb526c8684)

**Expected behavior**
可以免注册调用并不报错
**Screenshots**

**Desktop (please complete the following information):**
windows11
**Smartphone (please complete the following information):**

**Additional context**

**Comment by qianniancn** [comment]
需要把tess_model文件夹放到 插件目录下

**Comment by rwerplus** [comment]
thanks.
