### ISSUE TITLE
Windows中使用gdi模式绑定窗口后无法识别图片

### ISSUE THREAD

**Issue by rwerplus** [WallBreaker2/op#102]
**Describe the bug**

**To Reproduce**

当我使用gdi模式后无法识别图片,并且没有任何返回值
使用的是FindPicExS方法截图，其他方法也尝试过，但也是没有返回值
```
op.BindWindow(id, "gdi", "windows", "windows", 1)
op.FindPicExS(
        data.x1,
        data.y1,
        data.x2,
        data.y2,
        data.name,
        data.color_format,
        data.sim,
        0
      );
```
改为normal模式可以识别到
**Expected behavior**

**Screenshots**
![image](https://github.com/WallBreaker2/op/assets/48611415/b3fccdf0-4d4c-4c58-a2b5-8f813ab9dcd9)

**Desktop (please complete the following information):**
windows11
electron+nodejs
使用的是64位最新版op进行的调用
**Smartphone (please complete the following information):**

**Additional context**

**Comment by flaot** [comment]
先使用op.Capture接口查看输出的图片以确认截图是否正常

**Comment by rwerplus** [comment]
看起来只能在100%正常缩放条件下才能正确识别到

**Comment by flaot** [comment]
是的  这里的图像识别是以像素匹配为主要算法，缩放后每个像素跟匹配图就不一致了
