### ISSUE TITLE
綁定鍵盤後台成功，鍵盤功能全跳error

### ISSUE THREAD

**Issue by Ninisi** [WallBreaker2/op#123]
ret=op.BindWindow(_hwnd,"normal","normal","windows",0)
>>[ret=1]
op.KeyPress(70)
>>[datetime]x64info:error code=0
>>[datetime]x64info:error2 code=0
該遊戲受NProtect保護，
不知是否因為這樣，
該遊戲是Unity開發，我試過postmessage也是無效

**Comment by WallBreaker2** [comment]
是的，op插件内部也是使用send/post message方式模拟mouse & keypad
