### ISSUE TITLE
能不能弄一个chm帮助文档,让离线的我也可以学习使用

### ISSUE THREAD

**Issue by y5230024** [WallBreaker2/op#125]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by xonec** [comment]
https://github.com/WallBreaker2/op/wiki/
要不搜搜怎么把网页保存下来

**Comment by xonec** [comment]
离线说明
https://hogar.lanzouj.com/isSl51wx3nkd

**Comment by tianli-sir** [comment]
是由有后台点击事件
