### ISSUE TITLE
op_i.h和op_i.c如何生成呢？我自己编译源码, 发现是缺了这俩文件的

### ISSUE THREAD

**Issue by yanhuashengdian** [WallBreaker2/op#128]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by ggkkggk** [comment]
同問，找不到這二個文件，無法編譯

**Comment by WallBreaker2** [comment]
请注释源码根目录CMakeLists.txt中的以下代码：add_subdirectory("tools")以及add_subdirectory("tests")

**Comment by WallBreaker2** [comment]
下个commit将会修复这个问题
