### ISSUE TITLE
雷电模拟器3.122版本，只能用normal前台模式，后台模式截图要么是黑屏，要么是雷电开屏广告

### ISSUE THREAD

**Issue by Wetcland** [WallBreaker2/op#134]
雷电模拟器主窗口和子窗口，每个模式都测了一遍，结果如下
![image](https://github.com/WallBreaker2/op/assets/89971288/14c0735b-ae17-4e89-8d70-5a2dbbb96002)
以下是我的测试方法
![image](https://github.com/WallBreaker2/op/assets/89971288/9901b008-42e3-4961-a751-844b7ee17b11)

**Comment by xukai19941231** [comment]
雷电模拟器得绑定他内部的RenderWindow。另外好像得使用32位dll调试。
使用绑定测试工具能正常截图和点击。
绑定参数：hwnd,"dx2","windows","windows",0

**Comment by Wetcland** [comment]
> 雷电模拟器得绑定他内部的RenderWindow。另外好像得使用32位dll调试。 使用绑定测试工具能正常截图和点击。 绑定参数：hwnd,"dx2","windows","windows",0

我的不行，不知道为什么
