### ISSUE TITLE
Capture方法在屏幕缩放下有bug

### ISSUE THREAD

**Issue by sakuradon99** [WallBreaker2/op#148]
绑定的目标窗口
![image](https://github.com/WallBreaker2/op/assets/34861370/97c928fa-f07a-4d03-92f6-88ea82e950ad)

执行Golang代码
```
oleutil.MustCallMethod(o.object, "Capture", 0, 0, 2000, 1000, "test.bmp")
```

得到的截图不完整，Y轴的是完整的，但是X轴上左边的图被截掉了。我的屏幕是2k，缩放150%，看起来刚好左边就丢失了1/3的内容，当我把缩放调到100%的时候截图就是完整的
![image](https://github.com/WallBreaker2/op/assets/34861370/f284a221-a029-432d-a9a4-f165e7f3129c)

但是当我使用测试工具时截图又是正常的。
![image](https://github.com/WallBreaker2/op/assets/34861370/81a38508-9bc6-4ec1-aa70-f28f8331785f)

**Comment by qianniancn** [comment]
测试工具的开启了dpi感知，所以截图完整。

**Comment by sakuradon99** [comment]
> 测试工具的开启了dpi感知，所以截图完整。

我看dalao的PR还没合进去是么，所以现在的最新版release是不带DPI感知的？

**Comment by qianniancn** [comment]
借助 Windows api SetProcessDPIAware开启，坐标可能会有问题，自己换算一下
