### ISSUE TITLE
找图功能还可以优化一下吗

### ISSUE THREAD

**Issue by y5230024** [WallBreaker2/op#150]
因为我要找图的图片有细微的差别，用大漠和pyautogui置信度只要修改到0.8就能找到，使用op的话置信度要修改到0.3，这样很容易找到错误的位置，模糊匹配感觉还有待改进，当然用找多图的方法也能实现，就是麻烦，要穷举截图，不够智能，附件不能上传bmp,上传jpg给你测试一下，可能jpg的结果不能说明问题
![whz_看图王](https://github.com/WallBreaker2/op/assets/157140887/bf3671a9-f239-446b-8353-328fb4c99f97)
![whz2_看图王](https://github.com/WallBreaker2/op/assets/157140887/032f9388-00cb-4330-aa1f-3bff917be6d4)

**Comment by WallBreaker2** [comment]
请提供找图场景和需要找的图片

**Comment by zhonghai9967** [comment]
OP找图，同样的后台窗口大小，同样的图，速度最慢：
假如大漠找图需要1秒，OP需要3秒，aojia需要2秒
