### ISSUE TITLE
BindWindow 綁定 DirectX 11 遊戲視窗有問題

### ISSUE THREAD

**Issue by chang-chih-yao** [WallBreaker2/op#159]
平台：Win 11, python 3.10.14 (64bit)

遊戲介面是透過 DirectX 11 渲染的

前面的 dll 調用也是參考範例的：
`dll = ctypes.windll.LoadLibrary("data/tools.dll")`
`result = dll.setupW("data/op_x64.dll")`
都有成功

`r=self.op.BindWindow(game_win_hwnd, 'normal', 'normal', 'normal', 1)`
`print(r)`
前台截圖跟鍵鼠輸入都沒問題, 且 r 會是 1

但是後台輸入就會有問題
`r=self.op.BindWindow(game_win_hwnd, 'dx.d3d11', 'dx', 'windows', 1)`
`print(r)`
連 print(r) 都沒印出來，就會直接退出程序

請問是哪裡設定有問題嗎?

**Comment by pansuestc** [comment]
python进程可能崩溃了，请用[绑定工具](https://github.com/flaot/OPTestTool)测试一下

**Comment by WallBreaker2** [comment]
使用绑定工具测试试试

**Comment by chang-chih-yao** [comment]
使用 OPTestTool-0.4.5 ：
1. 使用系統管理員模式開啟 OPTestTool-0.4.5 (否則選遊戲視窗會錯誤)
2. 選擇遊戲視窗 -> 成功，可以選的到，hwnd 也是對的 (我用 spy++ 對過)
3. 
![image](https://github.com/user-attachments/assets/999fc312-7921-4ec6-874f-9c4450770aa6)

按下綁定後，OPTestTool-0.4.5 直接閃退，什麼 log 都沒有
這可能是什麼問題呢?

**Comment by chang-chih-yao** [comment]
我若選, normal, normal, normal 就可以綁定，沒有問題
但我只把 "鼠標" 改成 dx，就會直接閃退

**Comment by WallBreaker2** [comment]
已修复，请等待下次更新

**Comment by chang-chih-yao** [comment]
請問大概什麼時候會有新版更新呢?
