### ISSUE TITLE
为什么调用OCR的时候窗口最小化就无法识别到文字？

### ISSUE THREAD

**Issue by jonathanpeng** [WallBreaker2/op#17]
c#代码如下：
`int hwnd = opCom.FindWindow(string.Empty, "*无标题 - 记事本");

int flag = opCom.SetDict(0, @"E:\\Users\\Jon\\Desktop\\test.dict");

int result = opCom.BindWindow(hwnd, "normal", "normal", "normal", 0);

string ocrResult = opCom.Ocr(0, 0, 1600, 1024, "ffffff-000000", 1.0);`

把绑定的窗口切换到前台是正常的，最小化窗口就无法识别到文字。
color_format确定是对的,dict字典也是使用optool.exe抓图后手动定义的

**Comment by WallBreaker2** [comment]
最小化窗口不会刷新
