### ISSUE TITLE
经测试FindStr方法中待查找的字符串参数只可以一个中文字符

### ISSUE THREAD

**Issue by jonathanpeng** [WallBreaker2/op#18]
测试环境：win10专业版 1909 X64 版本号：18363.657
调用代码:
opCom.FindStr(0, 0, 1600, 1024, "银行", "ffffff-000000", 1.0, out x, out y);
返回0，输出参数 x,y都为-1
修改调用如下：
opCom.FindStr(0, 0, 1600, 1024, "银|行", "ffffff-000000", 1.0, out x, out y);
返回正常坐标点，
接口文档对此参数的描述：
string 字符串:待查找的字符串,可以是字符串组合，比如"长安|洛阳|大雁塔",中间用"|"来分割字符串
此为调用com接口方法，在此环境下只有绑定窗口前台激活才可以正常查找字符

**Comment by jonathanpeng** [comment]
突然想起来，这个应该和字典的设置有关，我制作的字典里每个字都是拆分开的

**Comment by WallBreaker2** [comment]
建议先用ocrex接口凑合
