### ISSUE TITLE
Com接口缺少SetKeypadDelay方法

### ISSUE THREAD

**Issue by jonathanpeng** [WallBreaker2/op#19]
错误信息：
错误	CS1061	'“IOpInterface”未包含“SetKeypadDelay”的定义，并且找不到可接受第一个“IOpInterface”类型参数的可访问扩展方法“SetKeypadDelay”(是否缺少 using 指令或程序集引用?)	

另外SetMouseDelay也没有，我是在调用KeyPress和KeyDown方法时有一些按钮无效所以想尝试增加延迟的方式，但是找不到这个方法

另外在测试按下F1键时发现lParam与手动按下键盘发送的参数不一致，用User32的PostMessage并处理lParam方法后是可以的
lParam处理方法是调用了MakeKeyLparam((int)keyval, 256);

**Comment by jonathanpeng** [comment]
SetMouseDelay也没有

**Comment by weituotian** [comment]
对啊，在仓库查找，IDE查找SetKeypadDelay都没有找到这个字符串
