### ISSUE TITLE
提交BUG

### ISSUE THREAD

**Issue by chenfnu** [WallBreaker2/op#2]
发现com注册成功后在delphi中导出接口时部分函数导不出来,导致无法调用比如SendString,SendStringIme,另外opencv_core343.dll, opencv_imgproc343.dll, zlib1.dll能不要么?拖几个尾巴有些麻烦

**Comment by WallBreaker2** [comment]
暂时不能

**Comment by WallBreaker2** [comment]
SendString,SendStringIme已修复

**Comment by WallBreaker2** [comment]
静态链接
