### ISSUE TITLE
0.3.5版本FingStr、FingStr、GetColor、CmpColor有问题

### ISSUE THREAD

**Issue by TheWind233** [WallBreaker2/op#23]
使用X64静态库lib调用
op.FindStr(0, 0, 800, 600, L"特殊奖励", L"ffacba-000000", 0.95, &x, &y, &ret);
op.GetColor(1848, 1058,wstr);
op.CmpColor(1848, 1058, L"e8524f-000000", 1.0,&ret)

FingStr、FingStr用dm工具生成的字库识别返回0，返回的x，y为-1。
GetColor不能获取到实际屏幕点的颜色。
CmpColor返回的是0，不管颜色是否匹配，

**Comment by WallBreaker2** [comment]
已修复

**Comment by TheWind233** [comment]
辛苦了

**Comment by nqzhang** [comment]
0.3.7 依旧有问题
x= self.dm.FindStr(777,282,814,306,"捉鬼","f2e91b-202020|928915-202020|d0c718-101010|716712-101010|f4ecc0-101010|c0af1e-101010",0.9)
print(x)

(0, -1, -1)

返回值是0 坐标都是-1
