### ISSUE TITLE
FindPic，FindPicEx的bug

### ISSUE THREAD

**Issue by yy10112002** [WallBreaker2/op#24]
同样的场景下，使用找图模式3但不限于该模式，在大区域范围内无法寻找到在指定小范围内能寻找到的图

ret,ret_x,ret_y=op:FindPic(0,0,1909,909,"rock3.bmp","101010",0.8,3);
0,1682,482

ret,ret_x,ret_y=op:FindPic(1790,698,1909,909,"rock3.bmp","101010",0.8,3);
0,1790,698

以下为素材：
rock3.bmp https://drive.google.com/file/d/1EyLk9tYIqemSFL2PjkSqi9hSJLS2FTds/view?usp=sharing
场景           https://drive.google.com/file/d/1-o3WeqxBco0u95ao2lI7_JqM47akoLqx/view?usp=sharing

**Comment by WallBreaker2** [comment]
加群细说
