### ISSUE TITLE
該dll是否支持Common Language Runtime (CLR)

### ISSUE THREAD

**Issue by Josh-Zhen** [WallBreaker2/op#28]
如題，因爲C#直接加載無法調用dll，非托管的dll，只能用注冊的方式，如果用免注冊的方式需要自己生成多一個類方法，略顯臃腫

**Comment by Josh-Zhen** [comment]
![image](https://user-images.githubusercontent.com/29705007/99936388-fc3e7880-2d9d-11eb-9181-6146ed289ad7.png)

**Comment by Josh-Zhen** [comment]
![image](https://user-images.githubusercontent.com/29705007/99936588-7242df80-2d9e-11eb-90be-a71be9339530.png)

**Comment by Josh-Zhen** [comment]
我用vs2019的頁面是這種
![image](https://user-images.githubusercontent.com/29705007/99940741-bdadbb80-2da7-11eb-8046-c310b78d92ab.png)

**Comment by WallBreaker2** [comment]
不支持，若要免注册使用，可在百度上c# com免注册相关内容
