### ISSUE TITLE
opengl后台截图 hook补充

### ISSUE THREAD

**Issue by w4454962** [WallBreaker2/op#36]
有的老游戏使用opengl， 进行后台截图 你hook的几个方法都没有生效， 经过调试发现可以通过 hook "glFinish" 来捕获绘制完成时 进行后台截屏。

**Comment by WallBreaker2** [comment]
请提供一下具体窗口

**Comment by w4454962** [comment]
百度下载 war3游戏  然后 创建war3.exe的快捷方式 用-opengl 参数启动游戏

**Comment by WallBreaker2** [comment]
已经加上了
