### ISSUE TITLE
文档里的方法有部分缺失

### ISSUE THREAD

**Issue by eatdemo** [WallBreaker2/op#4]
KeyPressChar，KeyPress方法没有，同时KeyDown、KeyDownChar、KeyUp、KeyUpChar无效
我的环境WIN7 64旗舰版 C#将dll注册到系统 通过COM引用。

**Comment by WallBreaker2** [comment]
这几个函数搞忘实现了，下次更新会修复的。

**Comment by WallBreaker2** [comment]
已更新
