### ISSUE TITLE
UseDict 函数返回1成功但其实没起作用

### ISSUE THREAD

**Issue by GitHubAFeng** [WallBreaker2/op#45]
如标题。我需要每次调用ocr前使用SetDict函数才行。
![image](https://user-images.githubusercontent.com/17705357/117744076-8db18200-b23a-11eb-8a89-c6dd2a7bf26e.png)

**Comment by WallBreaker2** [comment]
使用op对象做函数参数，会产生未定义行为

**Comment by WallBreaker2** [comment]
op对象不支持按值传递，因为每次都会构造新的op对象重新初始化。
