### ISSUE TITLE
弄了一个go语言调用op的库，方便go语言用户使用

### ISSUE THREAD

**Issue by kekeimiku** [WallBreaker2/op#46]
https://github.com/kekeimiku/op-go

活跃开发中，欢迎大佬们提建议修改代码

**Comment by WallBreaker2** [comment]
看了一下代码，基本功能都有了，很不错:)。注意到你使用com组件调用的op接口，性能可能比libop接口低一些,可以考虑使用[swig](http://www.swig.org/exec.html)包装libop接口，生成go语言的扩展库

**Comment by kekeimiku** [comment]
> 看了一下代码，基本功能都有了，很不错:)。注意到你使用com组件调用的op接口，性能可能比libop接口低一些,可以考虑使用[swig](http://www.swig.org/exec.html)包装libop接口，生成go语言的扩展库

因为看到其它语言也是com调用的接口，如果通过cgo调用比较麻烦，性能应该也不会更好，但是我没做过测试… 稍后会测试一下
