### ISSUE TITLE
建议增加dxgi截图模式（虚拟显卡屏幕监控），这个速度更快，更省CPU

### ISSUE THREAD

**Issue by xiaoyaocode163** [WallBreaker2/op#49]
建议增加dxgi截图模式，这个速度更快，更省CPU,dll体积也几乎很少增大。
这个相当于DirectX型的虚拟显卡驱动（win8以上系统微软自带）
我测试了用bitblt,3840*2160的全屏桌面普通方式截图要100毫秒，只截窗体只要40毫秒。
如果用DXGI，可能只要5-10毫秒。
可以采用事件机制，DLL里面回调。
比如屏幕变化小的情况，纯桌面操作（非游戏或视频），可能5秒10秒才有小区域图片变动。
有发生变动时，不需要再全屏进行找图。
假如屏幕中间坐标：Left,Top:1000,1200位置发生了W,H: 300*500像素的变化，要找的图片是 FindW,FindH:100*200，
那只需要对区域(X1,Y1;X2,Y2)(900,1000;1400,1900)进行找图，不需要全屏找图。
坐标区域算法：Left-findw,Top-FindH;Left+W+Findw;Top+h+FindH
---------------------
DXGI快速截屏录屏技术，高帧率直播桌面_HBStream流媒体与音视频技术-CSDN博客
https://blog.csdn.net/haibindev/article/details/84061641
很多地方都需要用到截屏/录屏技术，比如桌面直播，桌面录制等等。在微软Windows平台，有很多截屏的接口，不过大多数性能并不理想，
Windows8以后微软引入了一套新的接口，叫“Desktop Duplication API”，应用程序，可以通过这套API访问桌面数据。
而由于Desktop Duplication API是通过Microsoft DirectX Graphics Infrastructure (DXGI)来提供桌面图像的，速度非常快。由于是通过GPU，所以cpu占用率很低，性能很高

**Comment by WallBreaker2** [comment]
已添加：[commit](https://github.com/WallBreaker2/op/commit/af1f024c53a99ca48d489a965c6f3859b73d61a9)
