### ISSUE TITLE
BUG:较大图片，找图速度慢，优点：少量像素变化也能找到（大漠找不到）

### ISSUE THREAD

**Issue by xiaoyaocode163** [WallBreaker2/op#51]
表扬一下，OP对于图像有几个像素改动的都能认出来。
找大图宽高：1172,671，用时55秒（相似度80%，改成99%，一般1秒就找到了），找小图宽高：503,293，用时1秒。
目标物体在右下角：
OP库找图 坐标【2652,1424】937.6毫秒,相似度设置90%
OP库找图 坐标【2653,1424】223.8毫秒,相似度设置99%
OP库找图 坐标【67,230】171.4毫秒,相似度设置99%,目标物体在屏幕左上角

其实一个模糊找图的插件组件，应该返回实际识别匹配度，输入80%，实际匹配度是95%，方便开发者改进方法，统计数据。
场景：---------------
当要找的图片中间有几个污点或者少量细线或几个小矩形框，对要找的图来说，不同的部分可能还没有3%。
但是用大漠，乐玩等插件就完全认不到了，他们可能使用了少许的偏色等实现相似度。
对于要找的图像素有1-10个点不同就完全失灵了，相似度改成80%，50%都没用。
测试记录：------------
寻找屏幕区域：3840*2160
》》》找大图宽高：1172,671（相似度100%）
大漠找图 坐标【-1,-1】186.1毫秒
乐玩找图 坐标【-1,-1】209.3毫秒
OP库找图 坐标【-1,-1】564.0毫秒
===========================
》》》图上有杂点，设置：相似度80%，OP能找到

大漠找图 坐标【-1,-1】155.2毫秒
乐玩找图 坐标【-1,-1】232.5毫秒
OP库找图 坐标【2587,1430】55209.4毫秒

===============================================================
图上有个小圈（小图2_2653_1424.bmp），只有OP能找到
【图1272 只有OP找图能识别到图片上有污点或小划痕,线条，小方框.jpg】
寻找屏幕区域：3840*2160
小图宽高：503,293
相似度：90%

大漠找图 坐标【-1,-1】174.3毫秒
乐玩找图 坐标【-1,-1】232.1毫秒
OP库找图 坐标【2652,1423】1022.2毫秒

**Comment by WallBreaker2** [comment]
相识度为1时，找图速度和大漠相当，相识度小于1使用的模板匹配，计算量较大所以慢些，在最新版中采用了多线程计算，速度会稍快一些

**Comment by WallBreaker2** [comment]
0.4已解决
