### ISSUE TITLE
绑定雷电- 除了normal 其他都绑定不了, 所有opengl 都显示注入失败 

### ISSUE THREAD

**Issue by galaxymy** [WallBreaker2/op#53]
绑定雷电- 除了normal 其他都绑定不了, 所有opengl 都显示注入失败 
有没有解决方案

dm同样电脑测过ok

**Comment by WallBreaker2** [comment]
具体测试环境呢？比如op版本，雷电版本，操作系统等。我这边测试正常哦

**Comment by galaxymy** [comment]
3.0.9 win10 1809

我还自己编译了32bit  的 blackbone /MT 的lib 然后再编译了 最新op
还是老问题 就是 inject那个地方失败

用现成的版本， 直接闪退 也是inject后面那个地方  应该是blackbone那个 remote功能加载失败或者注入失败

**Comment by WallBreaker2** [comment]
很有可能是雷电版本的问题，op不支持32绑64的窗口

**Comment by galaxymy** [comment]
雷电也是用最新版本4.0.3x  你这边测的什么版本雷电 ok?我来测下

**Comment by galaxymy** [comment]
最新的 雷电4 和 雷电3 是不是都是 64的窗口？ 哪个版本是32的

**Comment by galaxymy** [comment]
可否添加一个 findpic/findmulticolor 功能 利用截图图片的 这样就不用绑定窗口， 直接对比窗口截图图片就行

**Comment by WallBreaker2** [comment]
请看这篇[博客](https://blog.csdn.net/qq_36144541/article/details/114497932?ops_request_misc=%257B%2522request%255Fid%2522%253A%2522162458341816780255289697%2522%252C%2522scm%2522%253A%252220140713.130102334..%2522%257D&request_id=162458341816780255289697&biz_id=0&utm_medium=distribute.pc_search_result.none-task-blog-2~all~sobaiduend~default-1-114497932.first_rank_v2_pc_rank_v29_1&utm_term=op%E6%8F%92%E4%BB%B6&spm=1018.2226.3001.4187)，介绍了如何绑定模拟器

**Comment by galaxymy** [comment]
根据那个页面 雷电3.104是ok的32bits 是吧 
然后那时用的是opengl  也可以用 最新dx.模式是吧

**Comment by WallBreaker2** [comment]
最新的没有测试过
