### ISSUE TITLE
FindMultiColor 闪退

### ISSUE THREAD

**Issue by galaxymy** [WallBreaker2/op#56]
findpic/ocr 测试正常

FindMultiColor

647, 56, 943, 147, "ffdf2d-101010", "0|-3|e2da5b-101010,0|-6|b0b5bb-101010", 0.90, 0

用的是以上参数 直接闪退

**Comment by WallBreaker2** [comment]
已经注意到这个问题，0.4.0版本会修复

**Comment by WallBreaker2** [comment]
0.4已更新，请前往gitee下载最新版
