### ISSUE TITLE
0.4.0 src 无法编译  缺很多文件 和上版本不一样

### ISSUE THREAD

**Issue by galaxymy** [WallBreaker2/op#59]
然后新接口 说明文档也没跟新

**Comment by galaxymy** [comment]
安装了 qt5 成功编译成 静态 .lib
但加载到exe里面 又无法编译, 出现3个 link 错误 2019

换成v3.9版本同样方案没问题?

v4.0 的.lib问题好像 缺了什么新的库lib?
=============
op_x86n.lib(libop.obj) : error LNK2019: unresolved external symbol ___std_system_error_allocate_message@8 referenced in function "public: virtual class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __thiscall std::_System_error_category::message(int)const " (?message@_System_error_category@std@@UBE?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@2@H@Z)

1>op_x86n.lib(libop.obj) : error LNK2019: unresolved external symbol ___std_system_error_deallocate_message@4 referenced in function "public: __thiscall std::_System_error_message::~_System_error_message(void)" (??1_System_error_message@std@@QAE@XZ)

1>op_x86n.lib(libop.obj) : error LNK2019: unresolved external symbol ___std_fs_convert_wide_to_narrow_replace_chars@20 referenced in function "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl std::filesystem::_Convert_wide_to_narrow_replace_chars<struct std::char_traits<char>,class std::allocator<char> >(enum __std_code_page,class std::basic_string_view<wchar_t,struct std::char_traits<wchar_t> >,class std::allocator<char> const &)" (??$_Convert_wide_to_narrow_replace_chars@U?$char_traits@D@std@@V?$allocator@D@2@@filesystem@std@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@1@W4__std_code_page@@V?$basic_string_view@_WU?$char_traits@_W@std@@@1@ABV?$allocator@D@1@@Z)

 fatal error LNK1120: 3 unresolved externals

**Comment by WallBreaker2** [comment]
0.4用的cmake工程，你需要使用cmake编译源代码，说明文档后续会更新
