### ISSUE TITLE
大神求助，关于按键精灵调用

### ISSUE THREAD

**Issue by zhaijp** [WallBreaker2/op#6]
请问你这个用按键精灵能调用吗?我试了一下32位的最新版，输出版本信息都没问题，但是move 不生效，不知道咋回事 代码如下

Set op = CreateObject("op.opsoft")
res = op.MoveTo (100,100 )
TracePrint res // 输出的是0

ver=op.Ver()
MsgBox ver //版本获取正确

**Comment by WallBreaker2** [comment]
试试0.3.3.0
