### ISSUE TITLE
绑定窗口后使用截图报错

### ISSUE THREAD

**Issue by qsc4442** [WallBreaker2/op#62]
![image](https://user-images.githubusercontent.com/6868865/124692431-2baa8b80-df10-11eb-880d-e9e429bc5621.png)

**Comment by CCCOVS** [comment]
我也遇到相同的情况,python 64位免注册,找图有时候会跳出这个,有时候又没有问题.

**Comment by WallBreaker2** [comment]
出现这种问题有两种情况
1. 窗口未完全加载的时候进行了绑定
2. 绑定窗口后。窗口大小发生了变化

**Comment by CCCOVS** [comment]
@WallBreaker2 首次启动的时候是好的,再次启动就报错了.OP0.4版本.python 64位免注册.win10

**Comment by WallBreaker2** [comment]
> 
> 
> @WallBreaker2 首次启动的时候是好的,再次启动就报错了.OP0.4版本.python 64位免注册.win10

重启重新绑

**Comment by CCCOVS** [comment]
@WallBreaker2 貌似每次要重启游戏后才能重新绑定,好像是模块没有被释放,有没有更高效的方法解决这个问题?
