### ISSUE TITLE
绑定的窗口关闭后会直接弹出错误提示窗口

### ISSUE THREAD

**Issue by chenmg2020** [WallBreaker2/op#68]
如果可以，希望增加一个，检测已绑定的窗口关闭后，先等待窗口重新开启并绑定后，再开始识别图片，这样就不会因为窗口关闭找图报错导致程序中断

**Comment by CCCOVS** [comment]
感觉轮询窗口是否存在并不是一个很好的建议.一方面吃内存,一方面影响识图效率.
我觉得你的需求应该是窗口关闭不让弹窗报错.可以试试.`op_ret = op.SetShowErrorMsg(0)`
你还可以利用多线程,其中有一条就一直轮询窗口是否存在,如果不存在,那么暂停主线程,并自动重启客户端啥的

**Comment by chenmg2020** [comment]
> ,并自动重启客户端啥

感谢建议，我会试试的，谢谢
