### ISSUE TITLE
请问op支持后台鼠标键盘操作吗?

### ISSUE THREAD

**Issue by igofreely** [WallBreaker2/op#69]
请问op支持后台鼠标键盘操作吗?

**Comment by CCCOVS** [comment]
> 请问op支持后台鼠标键盘操作吗?
赶紧把问题关了吧,windows消息模拟就是后台的唯一方式,没有之一..就算没看介绍.下个包,看看里面的说明文档也不至于问这样的问题..

不过这个插件对于游戏本身屏蔽后台消息模拟是没有办法的.按键精灵的后台也是如此.但如果是大漠的话,可以通过一些反屏蔽手段突破游戏不能后台的限制.

对比大漠,这个插件的优点是支持64位,没有大漠有名气, 大漠容易被针对性检测(这也是优点?).基本功能都有.

缺点是没有大漠完善, 毕竟大漠是商业软件,出来也早.这个bug略多.

-----------------------
写写千行以内的小脚本没问题.大型的暂不推荐.毕竟稳定比什么都重要.

**Comment by aneng1999** [comment]
不懂就问，这不是很正常的事吗？

**Comment by WallBreaker2** [comment]
后台模式只支持windows模式

**Comment by think8848** [comment]
> 不懂就问，这不是很正常的事吗？

貌似你这叫“懒”
