### ISSUE TITLE
建议找图增加个可以传原图的接口

### ISSUE THREAD

**Issue by 214175590** [WallBreaker2/op#7]
建议找图增加个可以传原图的接口，就是 类似  FindPic("图片路径"，"欲寻找的小图片路径",.....)
目前是只有绑定窗口找图，如果窗口不能截图（有些HOOK了API函数，禁止截图），那就找不了图了

**Comment by WallBreaker2** [comment]
谢谢你的建议，以后会考虑加的

**Comment by WallBreaker2** [comment]
已解决，使用SetDisplayInput接口即可
