### ISSUE TITLE
python调用op可以多线程吗？自测无法开启多线程

### ISSUE THREAD

**Issue by jiangxiaoyu007** [WallBreaker2/op#72]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by CCCOVS** [comment]
每个线程内都需要单独注册绑定操作.也就是有几个线程,就需要创建几个对象和对象的绑定.

**Comment by jiangxiaoyu007** [comment]
谢谢！
