### ISSUE TITLE
需要学习哪些技能可以参与到该项目开发

### ISSUE THREAD

**Issue by livis7** [WallBreaker2/op#80]

**Comment by WallBreaker2** [comment]
插件开发是一件比较繁琐的工作，需要大量技术的支持，下面是我的一些建议： 1. c++基础，推荐资料：c++primer(不用看完，只看核心部分即可) 2. stl常见容器和算法 3. windows编程 4. 其他技术（com组件,图像处理，hook技术等)

**Comment by livis7** [comment]
3ks
