### ISSUE TITLE
鼠标、键盘以windows方式绑定扫雷时，无法移动和点击

### ISSUE THREAD

**Issue by masker3-w** [WallBreaker2/op#82]
在绑定扫雷，op.BindWindow(hwnd, normal,windows,windows,0),鼠标 无法移动和点击

op.GetColor(x,y)  只有前台绑定才能获取颜色，后台绑定的基本都抓不到颜色。

为什么 GetScreenDataBmp 获取的图像，   用 C++是上下颠倒的 而用python却是正常的。
 
![GetScreenDataBmp](https://user-images.githubusercontent.com/74124220/233301514-e358a7df-7fec-499f-a31f-114026a8ecd3.jpg)

**Comment by masker3-w** [comment]
# import moudles
from win32com.client import Dispatch
import sys
import time;
import platform

print(platform.architecture())  #查看是32/64位

# create op instance
op = Dispatch("op.opsoft");
print(op.Ver())
print(op.GetBasePath())

#hwnd = op.FindWindow("CalcFrame","计算器");
hwnd = op.FindWindow("Minesweeper","扫雷");
print(hwnd)
if hwnd:
	ret = op.BindWindow(hwnd,"dx2","windows","windows",0);
	if ret == 1:
		print("bind ok");
		c = 0;
		
	else:
		print("bind false");
#op.RunApp("notepad",0);
op.MoveTo(100,100);
op.RightClick();
data = None;
size = 0;		
#op.Capture(0,0,200,200,"screen.bmp")
#data=op.GetScreenData(0, 0, 100, 100);
op.GetScreenDataBmp(0, 0, 200, 200, data, size);
print(data, type(data))
print(size, type(size))

获取不到数据？

**Comment by WallBreaker2** [comment]
请提供一下更明确的信息，例如os版本，插件版本等

**Comment by masker3-w** [comment]
> 请提供一下更明确的信息，例如os版本，插件版本等

OS： windows10 ltsc
插件：op 4.1.0
VS:  2019


![图片1](https://user-images.githubusercontent.com/74124220/234640623-9d637a1c-20fa-4eba-8831-140aa9b1589a.png)

**Comment by WallBreaker2** [comment]
已修复

**Comment by weedsacc** [comment]
我也正想反馈图像颠倒的问题,一看已经修复了
