### ISSUE TITLE
运行报错:x64info:Couid not initialize tesseract

### ISSUE THREAD

**Issue by ltxppp** [WallBreaker2/op#90]
运行examples下的VBS调用.vbs,必定报错x64info:Couid not initialize tesseract
系统是win10
在C:\Windows\SysWOW64中注册op_x64.dll

**Comment by WallBreaker2** [comment]
下个版本会解决这个问题

**Comment by WallBreaker2** [comment]
最新代码已解决此问题

**Comment by zhonghai9967** [comment]
2023.10.21,此问题仍未解决
