### ISSUE TITLE
qttool 请教如何编译

### ISSUE THREAD

**Issue by zelohon** [WallBreaker2/op#97]
大佬 帮忙指导一下 qttool 如何编译 非常感谢!

**Comment by WallBreaker2** [comment]
安装qt5，并参考readme中环境变量设置；然后将源码根目录的CMakelist.txt第18行由off改为on

**Comment by zelohon** [comment]
> 安装qt5，并参考ReadMe中环境变量设置;然后将源码根目录的CMakelist.txt第18行由off改为on

非常感谢！能麻烦在详细讲解下步骤吗  是使用qt5编译 还是使用vs编译？

**Comment by zelohon** [comment]
![H_1JFAU6F08D SA}1M_WOJ1](https://github.com/WallBreaker2/op/assets/36800197/b46684cd-5f0b-4dd6-ad2b-d7c1ec639465)

这个是哪里出错了？ 找了半天也没找到

**Comment by WallBreaker2** [comment]
使用vs编译 详细编译问题可以加群讨论
