### ISSUE TITLE
区域截图bug

### ISSUE THREAD

**Issue by zelohon** [WallBreaker2/op#98]
雷电模拟器  使用的绑定模式是  "dx2", "windows", "windows", 0      opengl模式会闪退  
绑定之后 全屏截图0,0,2000,2000 正常  选择一个区域截图763, 585, 863, 703    就会是黑背景的
就是说  x1 y1  如果不是设定0  就黑

**Comment by flaot** [comment]
无法复现  模式："dx2", "windows", "windows", 0
雷电模拟器 9.0.60(9)
Capture(554, 254,849, 412, "C:\\Test.bmp")  查看图是彩色图

**Comment by flaot** [comment]
修复dx2区域截图   #107
